### ISSUE TITLE
Addon stops sending data freezes frequently

### ISSUE THREAD

**Issue by mprreddy51** [splunk/ta-cisco-webex-meetings-add-on-for-splunk#13]
Hi,

I configured ta-cisco-webex-meetings-add-on-for-splunk addon and enabled meeting inputs. I noticed few things

1) Add-on pulls only 500 records and freezes,It works again after restarting Splunk service or disable and enable inputs and again freezes. checked CPU and Memory on the Heavy Forwarder and usage <50% (Heavy Forwarder Version : 7.2 Linux)
2) Can we remove limit 500 records or increase limit

Thanks

**Comment by mayurah** [comment]
@mprreddy51  **That's a strange behavior.** 

- Do you have any other agent installed on HWF?
- What is the pathway between HWF and WebEx?  Any proxy filter?

We can expose the limit parameter if you can help reproduce this (as we've not seen such an issue with recurring retrieval). 

For time being, you can manually edit below lines to change the Limit:

For General Service, Edit below:
— https://github.com/splunk/ta-cisco-webex-meetings-add-on-for-splunk/blob/master/bin/input_module_general_service.py#L74
For History Service, Edit below:
— https://github.com/splunk/ta-cisco-webex-meetings-add-on-for-splunk/blob/master/bin/input_module_history_service.py#L88


And ensure you delete `.PYC` file to avoid hitting code cache.


Could you provide us information on whether this is the cause of the issue?

**Comment by mprreddy51** [comment]
@mayurah 

I am running 3 more addons(ucs,gcp,salesforce) on that HF.

I also tried installing webex add-on on different server, same issue i noticed. Thanks

**Comment by mprreddy51** [comment]
This add-on is working perfectly fine in 8.x version. I have seen issue in 7.2.1 version.
