### ISSUE TITLE
Just need to know how to troubleshoot

### ISSUE THREAD

**Issue by vishaltaneja07011993** [splunk/ta-cisco-webex-meetings-add-on-for-splunk#16]
I am not getting any data, like, there is no error logs, how can i troublehsoot.

**Comment by mayurah** [comment]
@vishaltaneja07011993 - see if https://github.com/splunk/ta-cisco-webex-meetings-add-on-for-splunk/wiki/Troubleshooting helps!

**Comment by mayurah** [comment]
Re-open in case you still need help!
