### ISSUE TITLE
Introspection script failed

### ISSUE THREAD

**Issue by omerrudik** [splunk/ta-cisco-webex-meetings-add-on-for-splunk#3]
Hi,
Thanks for the add-on. I download and install it but after installation cannot navigate to the app TA page and see an error message on Splunk Messages: "Unable to initialize modular input "webex_meeting_log" defined in the app "ta-webex-meetings-add-on-for-splunk-master": Introspecting scheme=webex_meeting_logg: script running failed (exited with code 1).

I use Splunk 7.3,3 on linux with Java 8. 
The error was at your previous version (some days ago commit) and also at the latest TA version.
I also tried to comment the defination of python.version=3 on inputs.conf as python3 is supported only from Splunk 8 but it not work either.

My assumption is that there is some issue between the default\inputs.conf and README\inputs.conf\spec

Hope you can help with that.

**Comment by mayurah** [comment]
@omerrudik  Thanks for testing!

Could you tell us which TA Release/Version you used?

Happy to test it out.

**Comment by omerrudik** [comment]
Hi, 
Thanks for the reply.

I have checked version 1.0.2 build 3 (conf is under default\app.conf).

Omer.

**Comment by omerrudik** [comment]
Hi,

I tried now to check your new 1.1.1 version and the error continued.
Now it write: 
![image](https://user-images.githubusercontent.com/16244082/80695707-f53cd980-8ade-11ea-883f-d04b08cb9eb5.png)

"Unable to initialize modular input "history_service" defined in the app "ta_cisco_webex_meetings": Introspecting scheme=history_service: script running failed (exited with code 1)."

and when tring to navigate into the app, this is the result:
![image](https://user-images.githubusercontent.com/16244082/80695772-0be33080-8adf-11ea-9552-b5c548a1193f.png)

**Comment by mayurah** [comment]
**Could you try the below release?**

https://github.com/splunk/ta-cisco-webex-meetings-add-on-for-splunk/releases/download/1.1.1/ta-cisco-webex-meetings-add-on-for-splunk.tgz


I think the issue could be that you’re downloading it as source code and
trying to use that as TA!

Let us know the result! Happy to help.
-- 
Sent from mobile

**Comment by omerrudik** [comment]
@mayurah - great tip!
It is working now. 

Thanks a lot!
I will subscribe to retrieve more updates as I see you always release more versions.

Great work!
