### ISSUE TITLE
rename TA_cisco_webex_meetings_add_on_for_splunk_rh_settings.py

### ISSUE THREAD

**Issue by stboch** [splunk/ta-cisco-webex-meetings-add-on-for-splunk#7]
The script is uppercase however splunk is looking for the lowercase version. 

04-30-2020 17:59:52.191 -0400 ERROR AdminManagerDispatch - Cannot call handler 'ta_cisco_webex_meetings_add_on_for_splunk_settings' due to missing script 'ta_cisco_webex_meetings_add_on_for_splunk_rh_settings.py'.

**Comment by mayurah** [comment]
@stboch how did you install the TA? Via Latest Release or by downloading Source code?

**Comment by stboch** [comment]
Since the release is still not public it was via the sourcecode in the repo.

**Comment by mayurah** [comment]
@stboch thanks for the insight.

Please use "Latest Release" from release tab instead: https://github.com/splunk/ta-cisco-webex-meetings-add-on-for-splunk/releases/download/1.1.1/ta-cisco-webex-meetings-add-on-for-splunk.tgz

**Comment by stboch** [comment]
Ok releases download works fine. Thanks.
